//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Databases
    {
        public System.Guid Id { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public Nullable<System.DateTime> BackupDate { get; set; }
        public string Caption { get; set; }
        public string State { get; set; }
        public Nullable<System.Guid> TemplateId { get; set; }
        public int DbNumber { get; set; }
        public string ServiceName { get; set; }
        public string FilePath { get; set; }
        public string SqlName { get; set; }
        public string V82Name { get; set; }
        public string V82Server { get; set; }
        public int SizeInMB { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string LockedState { get; set; }
        public Nullable<bool> IsFile { get; set; }
        public string ArchivePath { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string WebPublishPath { get; set; }
        public string Platform { get; set; }
    }
}
